function [F, Cphi] = FreeEnergyBinary_FH(n1, s1, chi, kT, v, nA, V, n, gamma)

%Volume fractions and droplet size
phi1 = n1*nA/(n1*nA + s1);
V2 = V-(n1*nA + s1)*v;
phi2 = (n-n1)*nA*v / V2;

%Droplet surface area A
A = 36*pi^(1/3)*V2^(2/3);

F = (n1*nA + s1)*v*FreeEnergyDensityBinary_FH(phi1, chi, kT, v, nA) +...
    (V-(n1*nA + s1)*v)*FreeEnergyDensityBinary_FH(phi2, chi, kT, v, nA) + gamma*A;

c_phi11 = (1/((phi1 - phi2)^3))*(n*nA*v - V*phi2)*((phi1 - phi2)*((8*pi^(...
    1/3)*gamma*((-n*nA*v + V*phi1)/(phi1 - phi2))^(...
    2/3)*(5*n*nA*v + V*(-6*phi1 + phi2)))/(n*nA*v - ...
    V*phi1)^2 + (...
    kT*(phi2 + phi1*(1 - phi1 - phi2 + ...
    nA*(-2 + phi1 + phi2))))/(...
    nA*v*(-1 + phi1)*phi1)) - (...
    2*kT*(-1 + phi2)*log(1 - phi1))/v + (...
    2*kT*(phi2*log(phi1) + ...
    nA*(-1 + phi2)*log(1 - phi2) - phi2*log(phi2)))/(...
    nA*v));

c_phi12 = (1/(v*(phi1 - phi2)^3))*(kT*(n*nA*v*(-2 + phi1 + phi2) +...
    V*(phi1 + phi2 - 2*phi1*phi2))*log(1 - phi1) - (1/...
    nA)*((1/(n*nA*v -...
    V*phi1))*(phi1 - phi2)*(8*nA*pi^(1/3)*...
    v*gamma*((-n*nA*v + V*phi1)/(phi1 - phi2))^(...
    2/3)*(5*n*nA*v - 3*V*phi1 - 2*V*phi2) +...
    kT*(n*nA*v -...
    V*phi1)*((-1 + nA)*(2*n*nA*v - V*(phi1 + phi2)) -...
    nA*V*(phi1 - phi2)^2*chi)) +...
    kT*((-2*V*phi1*phi2 +...
    n*nA*v*(phi1 + phi2))*log(phi1) +...
    nA*(n*nA*v*(-2 + phi1 + phi2) +...
    V*(phi1 + phi2 - 2*phi1*phi2))*log(...
    1 - phi2) - (-2*V*phi1*phi2 +...
    n*nA*v*(phi1 + phi2))*log(phi2))));

c_phi22 = (1/(nA*v*(phi1 - phi2)^3))*((...
    1/((-1 + phi2)*phi2))*(phi1 - phi2)*(40*nA*pi^(1/3)*...
    v*gamma*((-n*nA*v + V*phi1)/(phi1 - phi2))^(...
    2/3)*(-1 + phi2)*phi2 +...
    kT*(n*nA*v -...
    V*phi1)*(phi1 + (-1 +...
    nA)*phi1*phi2 + phi2*(1 -...
    2*nA + (-1 + nA)*phi2))) -...
    2*kT*(n*nA*v -...
    V*phi1)*(nA*(-1 + phi1)*log(...
    1 - phi1) - phi1*log(phi1) -...
    nA*(-1 + phi1)*log(1 - phi2) + phi1*log(phi2)));


Cphi(1, 1) = c_phi11;
Cphi(1, 2) = c_phi12;
Cphi(2, 1) = c_phi12;
Cphi(2, 2) = c_phi22;

end